### ISSUE TITLE
plugins support the Android V2 embedding

### ISSUE THREAD

**Issue by javed19911** [fluttercommunity/flutter_uploader#202]
The plugins ` flutter_uploader' use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.

**Comment by sp-sivaprasad** [comment]
Please fix this issue or warning asap :)

**Comment by ened** [comment]
Resolved in main branch.

**Comment by jakehockey10** [comment]
Was a release for this every made?  I just added this library to our project and I'm still seeing this issue.

**Comment by wadihhannouch** [comment]
Same her @jakehockey10
